apiVersion: v1
kind: PersistentVolume
metadata:
  name: cka-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  claimRef:
    name: cka-pvc
    namespace: default
