apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cka-pod
  name: cka-pod
spec:
  containers:
  - image: nginx
    name: cka-pod
    resources: 
      limits:
        cpu: "0.5"
        memory: "20Mi" 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
