apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', "sleep 20"]

    