apiVersion: v1
kind: Pod
metadata:
  name: read-onlypod
spec:
  containers:
  - image: alpine
    name: read-onlypod
    command:
        - "sleep"
        - "3600"
    securityContext:
      readOnlyRootFilesystem: true      
    volumeMounts:
    - mountPath: /data
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      medium: Memory
      sizeLimit: 500Mi

