apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-add-settime-capability
  name: pod-add-settime-capability
spec:
  containers:
  - image: alpine
    name: pod-add-settime-capability
    command: ["sleep 3600"]  
    securityContext:
     capabilities:
      add: ["NET_ADMIN", "SYS_TIME"] 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
